# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource MobiusWork`

attributes:
  rights:
    type: string
    multiple: true
    index_keys:
      - "rights_tesim"
    form:
      required: false
      primary: false
      multiple: true
    predicate: http://purl.org/dc/terms/rightsHolder
    view:
      html_dl: true
    mappings:
      simple_dc_pmh: dc:rights
  relation:
    type: string
    multiple: true
    index_keys:
      - "relation_tesim"
    form:
      required: false
      primary: false
      multiple: true
    predicate: http://purl.org/dc/terms/relation
    view:
      html_dl: true
    mappings:
      simple_dc_pmh: dc:relation
  coverage:
    type: string
    multiple: true
    index_keys:
      - "coverage_tesim"
    form:
      required: false
      primary: false
      multiple: true
    predicate: http://purl.org/dc/terms/coverage
    view:
      html_dl: true
    mappings:
      simple_dc_pmh: dc:coverage
  file_format:
    type: string
    multiple: true
    index_keys:
      - "file_format_tesim"
    form:
      required: false
      primary: false
      multiple: true
    predicate: http://purl.org/dc/terms/FileFormat
    view:
      html_dl: true
    mappings:
      simple_dc_pmh: dc:format
